# Generated by Django 4.2.24 on 2026-09-28 14:07

from django.db import migrations, models


def backfill_bog(apps, schema_editor):
    # Every card order before this migration went through BOG.
    Order = apps.get_model('ecommerce_crm', 'Order')
    Order.objects.filter(bog_order_id__isnull=False).exclude(bog_order_id='').update(payment_provider='bog')


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0042_ecommercesettings_google_maps_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('bog', 'Bank of Georgia'), ('tbc', 'TBC Bank'), ('flitt', 'Flitt')], default='', help_text='Card gateway the order was charged through (empty for cash on delivery)', max_length=20),
        ),
        migrations.RunPython(backfill_bog, migrations.RunPython.noop),
    ]
