# Generated by Django 4.2.24 on 2026-10-08 09:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_crm', '0043_order_payment_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Crossed-out price for this variant only (so one colour can be on sale)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
