# Generated by Django 4.2.24 on 2026-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0050_paddle_multi_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPlatformRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('wechat', 'WeChat')], db_index=True, max_length=20)),
                ('external_id', models.CharField(db_index=True, help_text='Platform account id used in webhook payloads (page_id, instagram_account_id, phone_number_id, shop_id, …)', max_length=255)),
                ('tenant_schema', models.CharField(db_index=True, max_length=63)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Platform Route',
                'verbose_name_plural': 'Social Platform Routes',
                'db_table': 'tenants_social_platform_route',
                'indexes': [models.Index(fields=['platform', 'external_id', 'is_active'], name='tenants_soc_platfor_03eef6_idx')],
                'unique_together': {('platform', 'external_id')},
            },
        ),
    ]
