# Generated by Django 4.2.24 on 2026-08-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0052_deactivate_messages_beta_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatformroute',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('wechat', 'WeChat'), ('telegram', 'Telegram')], db_index=True, max_length=20),
        ),
    ]
