# Generated by Django 4.2.24 on 2026-05-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0053_widgetsession_ended_at_widgetsession_ended_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Reference to the message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social_integrations.instagrammessage'),
        ),
        migrations.AddField(
            model_name='instagrammessage',
            name='reply_to_message_id',
            field=models.CharField(blank=True, help_text='Message ID this is a reply to', max_length=255, null=True),
        ),
    ]
