# Generated by Django 4.2.24 on 2026-06-25 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0054_instagrammessage_reply_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppOutboundConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('opt_in_confirmed', models.BooleanField(default=False, help_text='Whether the agent confirmed the recipient opted in')),
                ('outcome', models.CharField(choices=[('sent', 'Sent'), ('blocked', 'Blocked'), ('failed', 'Failed')], max_length=20)),
                ('error_code', models.CharField(blank=True, help_text='Stable error code when outcome is blocked/failed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Agent who initiated the send', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_outbound_consent_logs', to=settings.AUTH_USER_MODEL)),
                ('business_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_consent_logs', to='social_integrations.whatsappbusinessaccount')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_consent_logs', to='social_integrations.whatsappmessagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_account', '-created_at'], name='social_inte_busines_932118_idx'), models.Index(fields=['to_number'], name='social_inte_to_numb_0d8052_idx')],
            },
        ),
    ]
