# Generated by Django 4.2.24 on 2026-07-22 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0055_whatsappoutboundconsentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='stale_assignment_reminder_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, agents get a popup reminder about assigned chats with no recent activity.'),
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='stale_assignment_reminder_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Minutes of inactivity before an assigned chat is considered stale (5–10080).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10080)]),
        ),
    ]
