# Generated by Django 4.2.24 on 2026-08-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_integrations', '0056_socialintegrationsettings_stale_assignment_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('platform_id', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cached Profile Picture',
                'verbose_name_plural': 'Cached Profile Pictures',
                'unique_together': {('platform', 'platform_id')},
            },
        ),
    ]
