# Generated by Django 4.2.24 on 2026-08-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0057_cachedprofilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpageconnection',
            name='connected_by',
            field=models.ForeignKey(blank=True, help_text='EchoDesk user whose session initiated the OAuth connect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_facebook_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='connected_by_fb_user_id',
            field=models.CharField(blank=True, default='', help_text='App-scoped Facebook user id that granted the page token', max_length=64),
        ),
        migrations.AddField(
            model_name='facebookpageconnection',
            name='webhook_subscribed',
            field=models.BooleanField(default=True, help_text='Whether the subscribed_apps webhook subscription succeeded at connect time'),
        ),
    ]
