# Generated by Django 4.2.24 on 2026-08-21 03:44

import crm.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0058_facebookpageconnection_connected_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text="The account's own Telegram user id", unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('username', models.CharField(blank=True, max_length=128)),
                ('profile_pic_url', models.URLField(blank=True, max_length=500, null=True)),
                ('session_string', crm.fields.EncryptedCharField()),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.CharField(blank=True, choices=[('manual', 'Manually Disconnected'), ('session_revoked', 'Session Revoked'), ('flood_wait', 'Flood Wait'), ('auth_error', 'Authentication Error'), ('api_error', 'API Error')], max_length=50, null=True)),
                ('deactivation_error', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last worker heartbeat for this account', null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('auto_disabled_at', models.DateTimeField(blank=True, help_text='Set when the system (not a human) disabled the account; requires re-login', null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, help_text='EchoDesk user who performed the login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_telegram_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Account',
                'verbose_name_plural': 'Telegram Accounts',
            },
        ),
        migrations.AddField(
            model_name='socialintegrationsettings',
            name='notification_sound_telegram',
            field=models.CharField(default='default', help_text='Sound identifier for Telegram notifications.', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatassignment',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok'), ('widget', 'Website widget'), ('telegram', 'Telegram')], help_text='Messaging platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationarchive',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok'), ('widget', 'Website widget'), ('telegram', 'Telegram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationautoreply',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], help_text='Messaging platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('tiktok', 'TikTok'), ('widget', 'Website widget'), ('telegram', 'Telegram')], max_length=20),
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('telegram_msg_id', models.BigIntegerField(db_index=True, help_text='Raw Telegram message id (per-account sequential)')),
                ('peer_id', models.BigIntegerField(db_index=True, help_text="Customer's Telegram user id — the conversation key")),
                ('peer_access_hash', models.BigIntegerField(blank=True, help_text='Telegram access_hash for the peer; required to send after worker restarts', null=True)),
                ('peer_name', models.CharField(blank=True, max_length=255)),
                ('peer_username', models.CharField(blank=True, max_length=128)),
                ('profile_pic_url', models.URLField(blank=True, max_length=500, null=True)),
                ('message_text', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Voice'), ('document', 'Document'), ('sticker', 'Sticker')], default='text', max_length=20)),
                ('media_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('media_mime_type', models.CharField(blank=True, max_length=100)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField()),
                ('is_from_business', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_read_by_staff', models.BooleanField(default=False)),
                ('read_by_staff_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('echodesk', 'EchoDesk'), ('telegram_app', 'Telegram App'), ('synced', 'Synced from History')], default='telegram_app', help_text='echodesk = sent from EchoDesk; telegram_app = echo of a message the owner sent from a Telegram client', max_length=20)),
                ('is_echo', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('reaction_emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('reacted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reacted_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deleted by staff')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social_integrations.telegramaccount')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_telegram_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='social_integrations.telegrammessage')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_telegram_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['account', 'timestamp'], name='social_inte_account_403a89_idx'), models.Index(fields=['account', 'peer_id', '-timestamp'], name='social_inte_account_8e01e6_idx')],
            },
        ),
    ]
