# Generated by Django 4.2.24 on 2026-08-24 11:41

import crm.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_integrations', '0059_telegramaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICompanionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master toggle for all AI companion behavior')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI')], default='anthropic', max_length=20)),
                ('model', models.CharField(blank=True, default='', help_text='Model id; empty = provider default', max_length=80)),
                ('api_key', crm.fields.EncryptedCharField(blank=True, default='', help_text='Tenant API key override; empty = platform default key')),
                ('guidance_prompt', models.TextField(blank=True, default='', help_text='Tenant instructions for how the AI should answer customers')),
                ('escalation_instructions', models.TextField(blank=True, default='', help_text='Extra instructions for when the AI should hand off to a human')),
                ('language', models.CharField(default='ka', help_text='Default reply language code (customer language still wins)', max_length=10)),
                ('max_replies_per_conversation_per_day', models.PositiveIntegerField(default=30)),
                ('max_replies_per_day', models.PositiveIntegerField(default=500, help_text='Tenant-wide daily AI reply cap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Companion Settings',
                'verbose_name_plural': 'AI Companion Settings',
            },
        ),
        migrations.CreateModel(
            name='AIConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('conversation_id', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('ai', 'AI Active'), ('needs_human', 'Needs Human'), ('off', 'Paused')], default='ai', max_length=20)),
                ('reason', models.TextField(blank=True, default='', help_text='Why the AI escalated (includes call requests)')),
                ('total_ai_replies', models.PositiveIntegerField(default=0)),
                ('daily_reply_count', models.PositiveIntegerField(default=0)),
                ('daily_count_date', models.DateField(blank=True, null=True)),
                ('last_ai_reply_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Conversation State',
                'verbose_name_plural': 'AI Conversation States',
                'indexes': [models.Index(fields=['platform', 'account_id', 'mode'], name='social_inte_platfor_7fbb95_idx')],
                'unique_together': {('platform', 'conversation_id', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='AICompanionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('reply', 'Reply Decision'), ('summary', 'Summary'), ('test', 'Settings Test')], max_length=20)),
                ('platform', models.CharField(blank=True, default='', max_length=20)),
                ('account_id', models.CharField(blank=True, default='', max_length=255)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('action', models.CharField(blank=True, default='', help_text='Decision outcome for reply runs: reply|handoff|ignore', max_length=30)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Companion Run',
                'verbose_name_plural': 'AI Companion Runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='social_inte_started_221e82_idx'), models.Index(fields=['kind', 'started_at'], name='social_inte_kind_dcaba4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AICompanionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('account_id', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('guidance_prompt', models.TextField(blank=True, default='', help_text='Channel-specific guidance; empty = inherit tenant default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Companion Channel',
                'verbose_name_plural': 'AI Companion Channels',
                'unique_together': {('platform', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('account_id', models.CharField(max_length=255)),
                ('conversation_id', models.CharField(max_length=255)),
                ('summary_text', models.TextField()),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation Summary',
                'verbose_name_plural': 'Conversation Summaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['platform', 'account_id', 'conversation_id', '-created_at'], name='social_inte_platfor_da7fa2_idx')],
            },
        ),
    ]
