# Generated by Django 4.2.24 on 2026-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0005_remove_bookingsettings_bog_client_id_booking_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manage_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Pay at the venue'), ('card', 'Card (online)')], default='', help_text='How the customer chose to pay (empty for bookings made before this field existed)', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='public_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='public_description',
            field=models.JSONField(blank=True, default=dict, help_text='Localized description: {"en": "...", "ka": "..."}'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='public_page_enabled',
            field=models.BooleanField(default=True, help_text='Let customers book online'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='public_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='timezone',
            field=models.CharField(default='Asia/Tbilisi', help_text='IANA timezone of the business', max_length=64),
        ),
    ]
