# Generated by Django 4.2.24 on 2026-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0006_public_booking_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_language',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
