# Generated by Django 4.2.24 on 2026-10-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0007_booking_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='second_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the second (closer) reminder was sent'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='_sms_api_key_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='reminder_hours_before',
            field=models.IntegerField(default=24, help_text='Send the reminder this many hours before the visit'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='second_reminder_hours_before',
            field=models.IntegerField(blank=True, help_text='Optional second reminder, closer to the visit', null=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_on_cancelled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_on_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_on_created',
            field=models.BooleanField(default=False, help_text='SMS when an online booking request arrives'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_on_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_on_rescheduled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_platform_monthly_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='sms_templates',
            field=models.JSONField(blank=True, default=dict, help_text='Custom texts: {"reminder": {"ka": "...", "en": "..."}}; missing = built-in default'),
        ),
        migrations.CreateModel(
            name='BookingSmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=20)),
                ('language', models.CharField(blank=True, max_length=5)),
                ('text', models.TextField()),
                ('segments', models.IntegerField(default=1)),
                ('account', models.CharField(blank=True, choices=[('own', "Salon's own key"), ('platform', 'Shared EchoDesk account'), ('', 'None')], max_length=10)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=10)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='booking_management.booking')),
            ],
            options={
                'db_table': 'booking_sms_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'status', 'created_at'], name='booking_sms_account_6a0abf_idx')],
            },
        ),
    ]
